In [1]:
import numpy as np
import pandas as pd

In [2]:
list1 = np.array(range(10))
list2 = pd.Series(range(10))

In [15]:
# Ejemplo de un array de numpy
list1 = np.array((1, 1, 2, 3, 4, 5))
print("---------Así se muestra un array de numpy---------")
print(list1)
print(f"El tipo de datos de un array de numpy es: {type(list1)}")

# Ejemplo de una serie de pandas
list2 = pd.Series((1,1,1,1,1,1,1,1,1, 2, 3, 4, 5))
print("---------Así se muestra una serie de pandas---------")
print(list2)
print(f"El tipo de datos de una serie de pandas es: {type(list2)}")


---------Así se muestra un array de numpy---------
[1 1 2 3 4 5]
El tipo de datos de un array de numpy es: <class 'numpy.ndarray'>
---------Así se muestra una serie de pandas---------
0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     2
10    3
11    4
12    5
dtype: int64
El tipo de datos de una serie de pandas es: <class 'pandas.core.series.Series'>


In [4]:
import time

In [ ]:
inicionp = time.time()

list3 = np.array(range(1000000))
print(np.mean(list3))
print(np.median(list3))

finnp = time.time()
print(finnp - inicionp)

499999.5
499999.5
0.07412195205688477


In [17]:
iniciopd = time.time()

list4 = pd.Series(range(1000000))
print(list4.mean())
print(list4.median())

finpd = time.time()
print(finpd - iniciopd)

499999.5
499999.5
0.023419618606567383


In [20]:
L = list(range(10))
L
print(type(L))

<class 'list'>


In [25]:
T = tuple(range(10))
T

print((T))

print("---------Así se muestra una tupla---------")

print(type(T))

(0, 1, 2, 3, 4, 5, 6, 7, 8, 9)
---------Así se muestra una tupla---------
<class 'tuple'>


In [26]:
import numpy as np

Npa = np.array(range(10))
Npa

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
Np_cero = np.zeros(10)
Np_cero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
Np_cero_int = np.zeros(10, dtype=int)
Np_cero_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [29]:
Np_uno = np.ones(10)
Np_uno

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
Np_relleno = np.full(10,256)
Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [31]:
Np_rango = np.arange(10)
Np_rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))
Np_random_dimensiones

array([[5, 3, 8, 6],
       [9, 4, 0, 0],
       [9, 2, 1, 9]])

In [38]:
# Verificando el tipo de dato de array
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
type(arr)

int64


numpy.ndarray

In [39]:
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

<U6


In [40]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [44]:
arr = np.array([1, 2, 3, 4], dtype='i')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [45]:
arr = np.array([1.1, 2.1, 3.1])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [46]:
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [47]:
Np_cero.ndim

1

In [48]:
Np_random_dimensiones.ndim

2

In [49]:
Np_random_dimensiones.shape

(3, 4)

In [50]:
Np_random_dimensiones.size

12

In [54]:
Np_cero.dtype

dtype('float64')

In [52]:
Np_cero_int.dtype

dtype('int64')

In [55]:
Np_random_dimensiones.itemsize

8

In [56]:
Np_cero.nbytes

80

In [ ]:
Np_cero_int.nbytes

80

In [60]:
rango = range(3,14)
print(rango)
print(type(rango))


print("-----------------")

Np_diez_numeros = np.array(rango)

print("-----------------")


Np_diez_numeros

range(3, 14)
<class 'range'>
-----------------
-----------------


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [64]:
print(Np_diez_numeros)
Np_diez_numeros[0]

[ 3  4  5  6  7  8  9 10 11 12 13]


3

In [65]:
print(Np_diez_numeros)
Np_diez_numeros[4]

[ 3  4  5  6  7  8  9 10 11 12 13]


7

In [66]:
Np_diez_numeros[-1]

13

In [67]:
Np_diez_numeros[-2]

12

In [68]:
Np_random_dimensiones

array([[5, 3, 8, 6],
       [9, 4, 0, 0],
       [9, 2, 1, 9]])

In [69]:
Np_random_dimensiones[2, 1]

2

In [70]:
Np_diez_numeros[:4]

array([3, 4, 5, 6])

In [71]:
Np_diez_numeros[3:]

array([ 6,  7,  8,  9, 10, 11, 12, 13])

In [72]:
Np_diez_numeros[4:7]

array([7, 8, 9])

In [73]:
Np_diez_numeros[::2]

array([ 3,  5,  7,  9, 11, 13])

In [74]:
Np_diez_numeros[::-2]

array([13, 11,  9,  7,  5,  3])

In [75]:
Np_random_dimensiones[2,]

array([9, 2, 1, 9])

In [76]:
Np_random_dimensiones[:2, :2]

array([[5, 3],
       [9, 4]])

In [77]:
Np_random_dimensiones[2, 3]

9

In [78]:
np.arange(1,65)
Ajedrez_64 = np.arange(1,65).reshape(8,8)
Ajedrez_64

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])

In [79]:
Array_1 = np.random.randint(10, size=5)
Array_2 = np.random.randint(10, size=5)
Arrays_concatenados = np.concatenate([Array_1, Array_2])
Arrays_concatenados

array([2, 9, 0, 2, 0, 1, 0, 7, 4, 3])

In [80]:
Array_extra = np.array([[10],[20]])
Array_extra

array([[10],
       [20]])

In [81]:
Array_apilados_v = np.vstack([Array_extra, Array_extra])
Array_apilados_v

array([[10],
       [20],
       [10],
       [20]])

In [82]:
Array_apilados_h = np.hstack([Array_extra, Array_extra])
Array_apilados_h

array([[10, 10],
       [20, 20]])

In [83]:
Arrays_concatenados

array([2, 9, 0, 2, 0, 1, 0, 7, 4, 3])

In [84]:
Array_partido = np.split(Arrays_concatenados, [2])
Array_partido

[array([2, 9]), array([0, 2, 0, 1, 0, 7, 4, 3])]

In [85]:
Array_partido_2 = np.split(Arrays_concatenados, [3, 8])
Array_partido_2

[array([2, 9, 0]), array([2, 0, 1, 0, 7]), array([4, 3])]

In [86]:
Parte_1, Parte_2, Parte_3 = Array_partido_2
Parte_1

array([2, 9, 0])

In [ ]:
Parte_2

array([7, 2, 0, 4, 4, 0])

In [ ]:
Parte_3

array([7, 6])

In [87]:
Ajedrez_partido_1 = np.hsplit(Ajedrez_64, [4])
Ajedrez_partido_1

[array([[ 1,  2,  3,  4],
        [ 9, 10, 11, 12],
        [17, 18, 19, 20],
        [25, 26, 27, 28],
        [33, 34, 35, 36],
        [41, 42, 43, 44],
        [49, 50, 51, 52],
        [57, 58, 59, 60]]),
 array([[ 5,  6,  7,  8],
        [13, 14, 15, 16],
        [21, 22, 23, 24],
        [29, 30, 31, 32],
        [37, 38, 39, 40],
        [45, 46, 47, 48],
        [53, 54, 55, 56],
        [61, 62, 63, 64]])]

In [88]:
Ajedrez_partido_2 = np.vsplit(Ajedrez_64, [4])
Ajedrez_partido_2

[array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29, 30, 31, 32]]),
 array([[33, 34, 35, 36, 37, 38, 39, 40],
        [41, 42, 43, 44, 45, 46, 47, 48],
        [49, 50, 51, 52, 53, 54, 55, 56],
        [57, 58, 59, 60, 61, 62, 63, 64]])]

In [98]:
Array_aleatorio = np.random.randint(10, size=10)
print(Array_aleatorio)
suma = 0
for i in Array_aleatorio:
    suma += i
promedio = suma / np.size(Array_aleatorio)

[1 9 9 4 0 1 3 6 4 2]


In [99]:
Array_aleatorio.sum()

39

In [100]:
Array_aleatorio.mean()

3.9

In [101]:
Array_aleatorio.max()

9

In [103]:
np.median(Array_aleatorio)

3.5

In [104]:
np.std(Array_aleatorio)

3.047950130825634

In [105]:
np.var(Array_aleatorio)

9.290000000000001

In [106]:
Array_1

array([2, 9, 0, 2, 0])

In [107]:
Array_2


array([1, 0, 7, 4, 3])

In [108]:
Array_1+5

array([ 7, 14,  5,  7,  5])

In [109]:
Array_1 + Array_2

array([3, 9, 7, 6, 3])

In [110]:
np.add(Array_1, Array_2)

array([3, 9, 7, 6, 3])

In [111]:
np.matmul(Array_1, Array_2)

10